//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18010
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurnSystems.WebServer {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_WebServer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_WebServer() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BurnSystems.WebServer.Localization_WebServer", typeof(Localization_WebServer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP-Präfix: {0} ähnelt.
        /// </summary>
        internal static string AddedPrefix {
            get {
                return ResourceManager.GetString("AddedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sessions werden aufgeräumt. ähnelt.
        /// </summary>
        internal static string CollectingSessions {
            get {
                return ResourceManager.GetString("CollectingSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d {
            get {
                object obj = ResourceManager.GetObject("d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d1 {
            get {
                object obj = ResourceManager.GetObject("d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot;
        ///       &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;BurnSystems Webserver&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;		
        ///			body
        ///			{
        ///				background-color: #00007F;
        ///				color: #FFFFFF;
        ///				margin: 20px;
        ///				font-family: &quot;Courier New&quot;, Courier, monospace
        ///			}
        ///		&lt;/style&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;@Model.Title&lt;/h1&gt;
        ///		&lt;p&gt;@Model.Url&lt;/p&gt;
        ///		&lt;p&gt;@Model.Message&lt;/p&gt;
        ///		@if(!string.IsNullOrE [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausnahme während des Listen-Vorgangs: {0} ähnelt.
        /// </summary>
        internal static string ExceptionDuringListening {
            get {
                return ResourceManager.GetString("ExceptionDuringListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausnahme während WebRequest &apos;{0}&apos;: {1} ähnelt.
        /// </summary>
        internal static string ExceptionDuringWebRequest {
            get {
                return ResourceManager.GetString("ExceptionDuringWebRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Hochladen von Dateien wird nicht unterstützt. ähnelt.
        /// </summary>
        internal static string FileUploadNotSupported {
            get {
                return ResourceManager.GetString("FileUploadNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde bereits ein Inhalt versandt. Ein weiteres Versenden ist nicht zulässig. ähnelt.
        /// </summary>
        internal static string FinishedSending {
            get {
                return ResourceManager.GetString("FinishedSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Starten des Webservers ist ein Fehler aufgetreten. Überprüfen Sie bitte ob folgende Dinge erfüllt sind:
        ///- Programm läuft mit Administratorrechte
        ///- Die angeforderte Website wird bereits von einer anderen Anwendung belegt.
        ///Die konkrete Fehlermeldung lautet: {0} ähnelt.
        /// </summary>
        internal static string HttpListenerException {
            get {
                return ResourceManager.GetString("HttpListenerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das übertragene Formular wurde nicht erkannt &apos;multipart/form-data&apos; ähnelt.
        /// </summary>
        internal static string InvalidMultipart {
            get {
                return ResourceManager.GetString("InvalidMultipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail &apos;{0}&apos; wurde zu &apos;{1}&apos; versendet.  ähnelt.
        /// </summary>
        internal static string MailSent {
            get {
                return ResourceManager.GetString("MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximale Länge des Requests überschritten: {0} Bytes (erlaubt: {1} Bytes) ähnelt.
        /// </summary>
        internal static string MaximumPostLengthExceeded {
            get {
                return ResourceManager.GetString("MaximumPostLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Webserver wurde bereits gestartet. ähnelt.
        /// </summary>
        internal static string ServerAlreadyStarted {
            get {
                return ResourceManager.GetString("ServerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Webserver wurde nicht gestartet.  ähnelt.
        /// </summary>
        internal static string ServerNotStarted {
            get {
                return ResourceManager.GetString("ServerNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sessions werden eingeladen. ähnelt.
        /// </summary>
        internal static string SessionsLoading {
            get {
                return ResourceManager.GetString("SessionsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Einladen der Sessions wurde folgende Ausnahme gefangen: {0} ähnelt.
        /// </summary>
        internal static string SessionsLoadingException {
            get {
                return ResourceManager.GetString("SessionsLoadingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sessions werden gespeichert. ähnelt.
        /// </summary>
        internal static string SessionsStoring {
            get {
                return ResourceManager.GetString("SessionsStoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Speichern der Sessions wurde folgende Ausnahme gefangen: {0} ähnelt.
        /// </summary>
        internal static string SessionsStoringException {
            get {
                return ResourceManager.GetString("SessionsStoringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail zu &apos;{0}&apos; wird wegen inaktivem MailSender nicht gesendet.  ähnelt.
        /// </summary>
        internal static string SkippingMail {
            get {
                return ResourceManager.GetString("SkippingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap throbber {
            get {
                object obj = ResourceManager.GetObject("throbber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
